### ISSUE TITLE
Enable support of QuakeLive bsp format

### ISSUE THREAD

**Issue by vityafx** [tcmal/rust-bsp#1]
The support of QuakeLive's `.bsp` format can easily be added by adding `0x2f` version support. The files are almost exactly the same, just one new lump for advertisement banners was added, according to other people reviews. I've already used other utilities and the `bsp` crate by just changing the byte to `0x2e` in files. However, I prefer this crate as it re-uses references and doesn't waste memory space, at least, tends to reuse it.

Could you please do this?

**Comment by tcmal** [comment]
Sure, I'll look into it.

**Comment by tcmal** [comment]
Will write tests as soon as I can.

**Comment by tcmal** [comment]
If you're happy with this I'll close the issue.

**Comment by vityafx** [comment]
Let me try it out today, okay? :) Nice work, by the way!

**Comment by vityafx** [comment]
Can't test, unfortunately. I'll reopen this when I'll be able to test and if it does not work. Thanks, much!
